name: Deploy Local Cluster

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to local Registry
        uses: docker/login-action@v1
        with:
          registry: https://hub.gunza.store
          username: ${{secrets.LOCAL_HUB_USERNAME}}
          password: ${{secrets.LOCAL_HUB_PASSWORD}}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            hub.gunza.store/gunza_dev/:latest
